# Generated by Django 5.1.1 on 2024-11-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comida_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('cardapio', models.ManyToManyField(related_name='eventos', to='core.comida')),
            ],
        ),
    ]
